 #spring:
 #  application:
 #    name: eurekaclient
 # cloud:
 #  config:
 #     uri: http://localhost:8888
 #     profile: developement
      
 spring:
   application:
     name: eurekaclient 
   zipkin:
    base-url: http://zipkin-server:9411
    
 server:
   port: 2222

 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      


   
  
